### ISSUE TITLE
The hyperlink of gcc-10.3.1 download is invalid

### ISSUE THREAD

**Issue by cnqpzhang** [AmpereComputing/ampere-gcc#2]
Download [ampere-aarch64-gcc-10.3.1-centos-8-18729.tgz](https://github.com/AmpereComputing/ampere-gcc/releases/download/ampere-8.3.0-20191025/ampere-aarch64-gcc-10.3.1-centos-8-18729.tgz)

**Comment by jiangning-liu-ampere** [comment]
Fixed.
