### ISSUE TITLE
compile SPEC CPU error using ampere-gcc

### ISSUE THREAD

**Issue by Algonquant** [AmpereComputing/ampere-gcc#3]
I use ampere-gcc 12.3 for SPEC CPU testing on Ampere Developers platform with host OS Ubuntu 22.04:
I set up gcc_dir to the gcc folder, but got follow error:

In file included from deb.c:25:
perl.h:714:10: fatal error: sys/types.h: No such file or directory
  714 | #include <sys/types.h>
      |          ^~~~~~~~~~~~~
compilation terminated.

Looks like the header files is missing. The compiling works will with gcc installed in original system.

**Comment by jiangning-liu-ampere** [comment]
Just uploaded ubuntu version at https://github.com/AmpereComputing/ampere-gcc/releases/download/ampere-12.3.0-20230515/ampere-aarch64-gcc-12.3.0-ubuntu-22-4f3dd1318aab-28426.tgz. Have a try, please!
