### ISSUE TITLE
How to use memory layout transformation optimization

### ISSUE THREAD

**Issue by xujiahao11** [AmpereComputing/ampere-gcc#4]
When I compile the program with the options -O3 -flto-partition=one -fipa-struct-reorg -fdump-ipa-all -fwhole-program, the generated assembly is the same as it was before adding -fipa-struct-reorg. Additionally, -fdump-ipa-all does not produce output for the "struct_reorg" pass. Although I can see the corresponding implementation in the source code, it doesn't seem to work.

**Comment by jiangning-liu-ampere** [comment]
This version of Ampere GCC is no longer supported.
